### PR TITLE
Generate types when custom schema present

### PR DESCRIPTION
**Pull request by ddgenome**
Generate types when either a custom schema is present or, as before,
when non-ingester GraphQL files are present.

### CODE REVIEW

**Comment by cdupuis** [comment]
Why would we need type generation when you don't have queries or subscriptions? How is that related to a custom schema?

**Comment by ddgenome** [comment]
@ipcrm requested this for the case where an SDM only defines custom types using ingesters but no queries or subscriptions. In these cases, he'd like to have the types and mutations associated with the custom types available in the SDM but there was no way to do this since we explicitly exclude ingesters when considering whether to generate types.

https://github.com/atomist/automation-client/pull/627/files#diff-60686b6914665329e0212d7fa32ab630R67

This resulted in people including spurious mutations wrapping the standard mutations created automatically with ingesters to get the types to get around this issue. Now, one just need to gql-fetch, which you would have to do anyway.

**Comment by cdupuis** [comment]
I still don't understand this. For what purpose would one need types if you are not using those to feed them into queries or mutations?

**Comment by ddgenome** [comment]
Because you want the _automatically generated_ mutations and their associated types available to you so you can call them in your code without defining a wrapper mutation that simply calls the automatically generated one.

**Comment by cdupuis** [comment]
> Because you want the _automatically generated_ mutations and their associated types available to you so you can call them in your code without defining a wrapper mutation that simply calls the automatically generated one.

But that doesn't actually work with the GraphClient. You have to define those mutation files.

**Comment by ddgenome** [comment]
It worked yesterday when we tested it.

**Comment by cdupuis** [comment]
> It worked yesterday when we tested it.

How do you call the `graphClient.mutate` function then?

**Comment by ipcrm** [comment]
``` const result = await ctx.context.graphClient.mutate<Mutation["ingestCustomSampleEvent"], MutationIngestCustomSampleEventArgs>({
                name: "ingestCustomSampleEvent",
                variables: {
                    value: {
                        message: `My new event!`,
                        timestamp: Date.now().toString(),
                    },
                },
            });```
Where `Mutation["ingestCustomSampleEvent"]` and `MutationIngestCustomSampleEventArgs` are automatically generated from the updated schema.

**Comment by cdupuis** [comment]
As I said, this doesn't work without a mutation file in the mutation folder:

```
2019-11-20T17:38:42.646Z [m:83318:6def8dfd-4577-47d0-9231-1636a8f6f398:Atomist Playground:helloworld:028] [error] Error: GraphQL file '/Users/cdupuis/atomist/projects/cdupuis/ingester-test/lib/graphql/mutation/ingestCustomSampleEvent.graphql' does not exist
    at locateAndLoadGraphql (/Users/cdupuis/atomist/projects/cdupuis/ingester-test/node_modules/@atomist/automation-client/src/lib/internal/graph/graphQL.ts:371:15)
    at Object.mutate (/Users/cdupuis/atomist/projects/cdupuis/ingester-test/node_modules/@atomist/automation-client/src/lib/internal/graph/graphQL.ts:157:13)
    at ApolloGraphClient.mutate (/Users/cdupuis/atomist/projects/cdupuis/ingester-test/node_modules/@atomist/automation-client/src/lib/graph/ApolloGraphClient.ts:121:35)
    at /Users/cdupuis/atomist/projects/cdupuis/ingester-test/lib/command.ts:11:38
    at Generator.next (<anonymous>)
    at /Users/cdupuis/atomist/projects/cdupuis/ingester-test/lib/command.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/cdupuis/atomist/projects/cdupuis/ingester-test/lib/command.js:4:12)
    at Object.listener (/Users/cdupuis/atomist/projects/cdupuis/ingester-test/lib/command.ts:10:26)
    at /Users/cdupuis/atomist/projects/cdupuis/ingester-test/node_modules/@atomist/sdm/src/lib/api-helper/machine/handlerRegistrations.ts:426:21
```

**Comment by ipcrm** [comment]
Happy to zoom with you about this; it does work with the changes @ddgenome is proposing.

**Comment by cdupuis** [comment]
@ipcrm can we close this now?

**Comment by ipcrm** [comment]
Yep!

**Pull request closed without merging**
