### PR TITLE
Fix globbing of client config

### PR DESCRIPTION
**Pull request by cdupuis**
The previous code wasn't working on Windows which this change fixes.

### CODE REVIEW

**Review by ipcrm — APPROVED** [review]
thx @cdupuis

**Review by ddgenome — COMMENTED** [review]
LGTM.

Are the testing failures worrisome?

**Comment by cdupuis** [comment]
> Are the testing failures worrisome?

Those are unrelated but I perhaps they occur in main branch as well.

**Comment by ddgenome** [comment]
The timeouts likely just need to be increased.

**Pull request merged**
