### PR TITLE
Make http base path configurable

### PR DESCRIPTION
**Pull request by cdupuis**

### CODE REVIEW

**Review by ddgenome — COMMENTED** [review]
Looks good. Should `configuration.http.base` be defined here: https://github.com/atomist/automation-client/blob/5c6988381c062fd8039b11c51603c6608e262b4c/lib/configuration.ts#L162 ?

**Comment by cdupuis** [comment]
> Looks good. Should `configuration.http.base` be defined here:
> 
> https://github.com/atomist/automation-client/blob/5c6988381c062fd8039b11c51603c6608e262b4c/lib/configuration.ts#L162
> 
> ?

Isn't that in the `Partial<ExpressServerOptions>;`?

**Comment by ddgenome** [comment]
Indeed it is.

**Review by ddgenome — APPROVED** [review]
LGTM

**Pull request merged**
